# Generated by Django 4.2.6 on 2024-01-02 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='announcement_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=50)),
                ('announcement', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='book_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('publish_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='course_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HOD_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HOD_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='student_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=200)),
                ('roll_number', models.CharField(max_length=50)),
                ('student_course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='page_handler.course_model')),
            ],
        ),
        migrations.CreateModel(
            name='teacher_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=200)),
                ('HOD', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='page_handler.hod_model')),
                ('teacher_course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='page_handler.course_model')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.BinaryField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_handler.teacher_model')),
            ],
        ),
        migrations.CreateModel(
            name='Student_picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.BinaryField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_handler.student_model')),
            ],
        ),
        migrations.AddField(
            model_name='student_model',
            name='student_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='page_handler.teacher_model'),
        ),
        migrations.CreateModel(
            name='student_attendance_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_attendance', models.DateField()),
                ('mark_attendance', models.BooleanField(default=False)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='page_handler.student_model')),
            ],
        ),
        migrations.CreateModel(
            name='HOD_picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.BinaryField()),
                ('HOD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_handler.hod_model')),
            ],
        ),
        migrations.AddField(
            model_name='course_model',
            name='HOD_undertaken',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='page_handler.hod_model'),
        ),
        migrations.CreateModel(
            name='book_issue_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='page_handler.book_model')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='page_handler.student_model')),
            ],
        ),
    ]
