# Generated by Django 4.2.6 on 2024-01-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_handler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hod_picture',
            name='picture',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
