# Generated by Django 4.2.6 on 2024-01-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_handler', '0002_alter_hod_picture_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hod_picture',
            name='picture',
            field=models.ImageField(upload_to='HOD_picture/'),
        ),
        migrations.AlterField(
            model_name='student_picture',
            name='picture',
            field=models.ImageField(upload_to='Student_picture/'),
        ),
        migrations.AlterField(
            model_name='teacher_picture',
            name='picture',
            field=models.ImageField(upload_to='Teacher_picture/'),
        ),
    ]
